//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseProject_7_0.App_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vocabulary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vocabulary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseProject_7_0.App_Resources.Vocabulary", typeof(Vocabulary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Our Cosmetic Surgery Center.
        /// </summary>
        public static string AboutOurCosmeticSurgeryCenter {
            get {
                return ResourceManager.GetString("AboutOurCosmeticSurgeryCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The Center.
        /// </summary>
        public static string AboutTheCenter {
            get {
                return ResourceManager.GetString("AboutTheCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About This Special.
        /// </summary>
        public static string AboutThisSpecial {
            get {
                return ResourceManager.GetString("AboutThisSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AcademicInfo {
            get {
                return ResourceManager.GetString("AcademicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Surgical Facility.
        /// </summary>
        public static string AccreditedSurgicalFacility {
            get {
                return ResourceManager.GetString("AccreditedSurgicalFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchool.
        /// </summary>
        public static string Alchool {
            get {
                return ResourceManager.GetString("Alchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergies?.
        /// </summary>
        public static string Allergies {
            get {
                return ResourceManager.GetString("Allergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to America.
        /// </summary>
        public static string America {
            get {
                return ResourceManager.GetString("America", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string ApplyNow {
            get {
                return ResourceManager.GetString("ApplyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArmLift.
        /// </summary>
        public static string ArmLift {
            get {
                return ResourceManager.GetString("ArmLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AskAndLetUsHelpYourSentence {
            get {
                return ResourceManager.GetString("AskAndLetUsHelpYourSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask for your options.
        /// </summary>
        public static string AskForYourOptions {
            get {
                return ResourceManager.GetString("AskForYourOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Avana, we strive to meet and exceed your expectations. Our practice delivers excellent surgical care with great compassion and respect and our surgeons utilize the most advanced techniques to produce the best results possible....
        /// </summary>
        public static string AtAvana {
            get {
                return ResourceManager.GetString("AtAvana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avana Plastic Surgery - Tour our Miami Facility.
        /// </summary>
        public static string AvanaPlasticSurgeryTourOurMiamiFacility {
            get {
                return ResourceManager.GetString("AvanaPlasticSurgeryTourOurMiamiFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Bankruptcy {
            get {
                return ResourceManager.GetString("Bankruptcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BankruptcyProfessional {
            get {
                return ResourceManager.GetString("BankruptcyProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before And After By.
        /// </summary>
        public static string BeforeAndAfterBy {
            get {
                return ResourceManager.GetString("BeforeAndAfterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before And After Pictures.
        /// </summary>
        public static string BeforeAndAfterPictures {
            get {
                return ResourceManager.GetString("BeforeAndAfterPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Prices in Miami Area.
        /// </summary>
        public static string BestPrices {
            get {
                return ResourceManager.GetString("BestPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BlogPosts {
            get {
                return ResourceManager.GetString("BlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI of.
        /// </summary>
        public static string BMIOf {
            get {
                return ResourceManager.GetString("BMIOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a Consultation.
        /// </summary>
        public static string BookConsultation {
            get {
                return ResourceManager.GetString("BookConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botox.
        /// </summary>
        public static string Botox {
            get {
                return ResourceManager.GetString("Botox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Augmentation.
        /// </summary>
        public static string BreastAugmentation {
            get {
                return ResourceManager.GetString("BreastAugmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Lift.
        /// </summary>
        public static string BreastLift {
            get {
                return ResourceManager.GetString("BreastLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Reduction.
        /// </summary>
        public static string BreastReduction {
            get {
                return ResourceManager.GetString("BreastReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Hours.
        /// </summary>
        public static string BusinessHours {
            get {
                return ResourceManager.GetString("BusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATE YOUR BMI.
        /// </summary>
        public static string CalculateYouBMI {
            get {
                return ResourceManager.GetString("CalculateYouBMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us or send us your information and we will contact you soon..
        /// </summary>
        public static string CallOrContact {
            get {
                return ResourceManager.GetString("CallOrContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Policy.
        /// </summary>
        public static string CancellationPolicy {
            get {
                return ResourceManager.GetString("CancellationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we contact you via email with special offers?.
        /// </summary>
        public static string CanWeContactYouViaEmailWithSpecialOffers {
            get {
                return ResourceManager.GetString("CanWeContactYouViaEmailWithSpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can we contact you via sms with special offers?.
        /// </summary>
        public static string CanWeContactYouViaSmsWithSpecialOffers {
            get {
                return ResourceManager.GetString("CanWeContactYouViaSmsWithSpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chek.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Our Instagram.
        /// </summary>
        public static string CheckOurInstagram {
            get {
                return ResourceManager.GetString("CheckOurInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childbirths.
        /// </summary>
        public static string Childbirths {
            get {
                return ResourceManager.GetString("Childbirths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cigarretes.
        /// </summary>
        public static string Cigarretes {
            get {
                return ResourceManager.GetString("Cigarretes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        public static string Commitment {
            get {
                return ResourceManager.GetString("Commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConsentParagraph {
            get {
                return ResourceManager.GetString("ConsentParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consultation room.
        /// </summary>
        public static string ConsultationRoom {
            get {
                return ResourceManager.GetString("ConsultationRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ConsultUs {
            get {
                return ResourceManager.GetString("ConsultUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us or give us a call to discover how we can help.
        /// </summary>
        public static string ContactUsOrGiveUsACallToDiscoverHowWeCanHelp {
            get {
                return ResourceManager.GetString("ContactUsOrGiveUsACallToDiscoverHowWeCanHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us to schedule your surgery today..
        /// </summary>
        public static string ContactUSTo {
            get {
                return ResourceManager.GetString("ContactUSTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID-19 Crisis.
        /// </summary>
        public static string COVID19Crisis {
            get {
                return ResourceManager.GetString("COVID19Crisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Criminal {
            get {
                return ResourceManager.GetString("Criminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CriminalProfessional {
            get {
                return ResourceManager.GetString("CriminalProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Essay {
            get {
                return ResourceManager.GetString("Essay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellence and Experience in cosmetic surgery in Miami.
        /// </summary>
        public static string ExcellenceandExperienceincosmeticsurgeryinMiami {
            get {
                return ResourceManager.GetString("ExcellenceandExperienceincosmeticsurgeryinMiami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ExpectedGraduationDate {
            get {
                return ResourceManager.GetString("ExpectedGraduationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain.
        /// </summary>
        public static string Explain {
            get {
                return ResourceManager.GetString("Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaceLift.
        /// </summary>
        public static string FaceLift {
            get {
                return ResourceManager.GetString("FaceLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FAQS {
            get {
                return ResourceManager.GetString("FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string Feet {
            get {
                return ResourceManager.GetString("Feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCING OPTIONS.
        /// </summary>
        public static string FinacingOptions {
            get {
                return ResourceManager.GetString("FinacingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCING.
        /// </summary>
        public static string Financing {
            get {
                return ResourceManager.GetString("Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing Available.
        /// </summary>
        public static string FinancingAvailable {
            get {
                return ResourceManager.GetString("FinancingAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have the best.
        /// </summary>
        public static string Financingcalltoaction1 {
            get {
                return ResourceManager.GetString("Financingcalltoaction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to financing options.
        /// </summary>
        public static string Financingcalltoaction2 {
            get {
                return ResourceManager.GetString("Financingcalltoaction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for you..
        /// </summary>
        public static string Financingcalltoaction3 {
            get {
                return ResourceManager.GetString("Financingcalltoaction3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it’s easier than ever to pay for cosmetic surgery costs, click on the button and see our plans..
        /// </summary>
        public static string Financingcalltoaction4 {
            get {
                return ResourceManager.GetString("Financingcalltoaction4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special low interest financing is available on approved credit.
        /// </summary>
        public static string FinancingTagline {
            get {
                return ResourceManager.GetString("FinancingTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Avana Bariatric Surgery, we offer attractive financing options through CareCredit, United Medical and Alphaeon. These options cover expenses not covered by medical insurance. With instant approval, no activation fee, and competitive interest rates for short-term and long-term financing. Other financing options may be available upon request..
        /// </summary>
        public static string Financingtext {
            get {
                return ResourceManager.GetString("Financingtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuentra los mejores precios para tu procedimiento.
        /// </summary>
        public static string FindYourProcedure {
            get {
                return ResourceManager.GetString("FindYourProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a.
        /// </summary>
        public static string ForA {
            get {
                return ResourceManager.GetString("ForA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For The Keyword.
        /// </summary>
        public static string ForTheKeyword {
            get {
                return ResourceManager.GetString("ForTheKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Consultation.
        /// </summary>
        public static string FreeConsultation {
            get {
                return ResourceManager.GetString("FreeConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Desk.
        /// </summary>
        public static string FrontDesk {
            get {
                return ResourceManager.GetString("FrontDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastric Sleeve Surgery.
        /// </summary>
        public static string GastricSleeveSurgery {
            get {
                return ResourceManager.GetString("GastricSleeveSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Approved Now.
        /// </summary>
        public static string GetApprovedNow {
            get {
                return ResourceManager.GetString("GetApprovedNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in.
        /// </summary>
        public static string GetIn {
            get {
                return ResourceManager.GetString("GetIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready.
        /// </summary>
        public static string Gettingready {
            get {
                return ResourceManager.GetString("Gettingready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight loss surgery is not for everyone. Individuals who abuse medicines or alcohol, for example, may not be able to commit to permanent lifestyle changes. Before having surgery, we educate our patients so that they know exactly what to expect. You will receive nutritional counseling, a psychological evaluation, and a variety of physical exams, blood tests, upper endoscopy or imaging studies of your stomach before undergoing sleeve gastrectomy. Patients that smoke must stop several months before surgery. Al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Gettingreadytext {
            get {
                return ResourceManager.GetString("Gettingreadytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gynocomastia.
        /// </summary>
        public static string Gynocomastia {
            get {
                return ResourceManager.GetString("Gynocomastia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have A Look Around.
        /// </summary>
        public static string HaveALookAround {
            get {
                return ResourceManager.GetString("HaveALookAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAVE A QUESTION.
        /// </summary>
        public static string HaveAQuestion {
            get {
                return ResourceManager.GetString("HaveAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Conditions?.
        /// </summary>
        public static string HealthConditions {
            get {
                return ResourceManager.GetString("HealthConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health first.
        /// </summary>
        public static string Healthfirst {
            get {
                return ResourceManager.GetString("Healthfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The benefits of gastric sleeve surgery go beyond just weight loss and encompass both the patient’s physical and emotional wellbeing..
        /// </summary>
        public static string Healthfirsttext {
            get {
                return ResourceManager.GetString("Healthfirsttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Many?.
        /// </summary>
        public static string HowMany {
            get {
                return ResourceManager.GetString("HowMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Often?.
        /// </summary>
        public static string HowOften {
            get {
                return ResourceManager.GetString("HowOften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IHerebyText {
            get {
                return ResourceManager.GetString("IHerebyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included 1 Night Hospital stay and 1 year of Follow Ups..
        /// </summary>
        public static string Included9000 {
            get {
                return ResourceManager.GetString("Included9000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included 1 Night Hospital stay, 7 days and 6 Night Recovery Home Package and 1 year of Follow Ups.
        /// </summary>
        public static string Included9900 {
            get {
                return ResourceManager.GetString("Included9900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit our Instagram and take a look on some of our before and after pictures, videos, comments, testimonials, and more..
        /// </summary>
        public static string InstagramPostsSubtitle {
            get {
                return ResourceManager.GetString("InstagramPostsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In The News.
        /// </summary>
        public static string InTheNews {
            get {
                return ResourceManager.GetString("InTheNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In This Page.
        /// </summary>
        public static string InThisPage {
            get {
                return ResourceManager.GetString("InThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is currently.
        /// </summary>
        public static string IsCurrently {
            get {
                return ResourceManager.GetString("IsCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Hair Removal.
        /// </summary>
        public static string LaserHairRemoval {
            get {
                return ResourceManager.GetString("LaserHairRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More About How You Can Stay With Us.
        /// </summary>
        public static string LearnMoreOutOfTown {
            get {
                return ResourceManager.GetString("LearnMoreOutOfTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LegalVideos {
            get {
                return ResourceManager.GetString("LegalVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Changing Results.
        /// </summary>
        public static string LifeChangingResults {
            get {
                return ResourceManager.GetString("LifeChangingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liposuction.
        /// </summary>
        public static string Liposuction {
            get {
                return ResourceManager.GetString("Liposuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M/F.
        /// </summary>
        public static string MaleOrFemale {
            get {
                return ResourceManager.GetString("MaleOrFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max BMI For A BBL.
        /// </summary>
        public static string MaxBMIForABBL {
            get {
                return ResourceManager.GetString("MaxBMIForABBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Accepted BMI by Doctors for a.
        /// </summary>
        public static string MaximumAcceptedBMIByDoctorsForA {
            get {
                return ResourceManager.GetString("MaximumAcceptedBMIByDoctorsForA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May Contain Nudity.
        /// </summary>
        public static string MayContainNudity {
            get {
                return ResourceManager.GetString("MayContainNudity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Content.
        /// </summary>
        public static string MediaContent {
            get {
                return ResourceManager.GetString("MediaContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet the Staff.
        /// </summary>
        public static string MeetTheStaff {
            get {
                return ResourceManager.GetString("MeetTheStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent Successfully!.
        /// </summary>
        public static string MessageSentSuccessfully {
            get {
                return ResourceManager.GetString("MessageSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday through Friday.
        /// </summary>
        public static string MondayThroughFriday {
            get {
                return ResourceManager.GetString("MondayThroughFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NeedToKnowMore {
            get {
                return ResourceManager.GetString("NeedToKnowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Surgical.
        /// </summary>
        public static string NonSurgical {
            get {
                return ResourceManager.GetString("NonSurgical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Hours.
        /// </summary>
        public static string OfficeHours {
            get {
                return ResourceManager.GetString("OfficeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Map.
        /// </summary>
        public static string OpenInMap {
            get {
                return ResourceManager.GetString("OpenInMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our1 {
            get {
                return ResourceManager.GetString("Our1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OurFirm {
            get {
                return ResourceManager.GetString("OurFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Office.
        /// </summary>
        public static string OurOffice {
            get {
                return ResourceManager.GetString("OurOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Procedures.
        /// </summary>
        public static string OurProcedures {
            get {
                return ResourceManager.GetString("OurProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OurProfessionals {
            get {
                return ResourceManager.GetString("OurProfessionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Surgeons.
        /// </summary>
        public static string OurSurgeons {
            get {
                return ResourceManager.GetString("OurSurgeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team is waiting for your concerns or questions..
        /// </summary>
        public static string OurTeam {
            get {
                return ResourceManager.GetString("OurTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT OF TOWN PATIENTS.
        /// </summary>
        public static string OutOfTownPatients {
            get {
                return ResourceManager.GetString("OutOfTownPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out the range accepted.
        /// </summary>
        public static string OutTheRangeAccepted {
            get {
                return ResourceManager.GetString("OutTheRangeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Portal.
        /// </summary>
        public static string PatientPortal {
            get {
                return ResourceManager.GetString("PatientPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Resources.
        /// </summary>
        public static string PatientResources {
            get {
                return ResourceManager.GetString("PatientResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersonalInjury {
            get {
                return ResourceManager.GetString("PersonalInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PersonalInjuryProfessional {
            get {
                return ResourceManager.GetString("PersonalInjuryProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Surgeon.
        /// </summary>
        public static string PlasticSurgeon {
            get {
                return ResourceManager.GetString("PlasticSurgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Surgeons.
        /// </summary>
        public static string PlasticSurgeons {
            get {
                return ResourceManager.GetString("PlasticSurgeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string PleaseEnterAValidEmailAddress {
            get {
                return ResourceManager.GetString("PleaseEnterAValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the phone.
        /// </summary>
        public static string PleaseEnterThePhone {
            get {
                return ResourceManager.GetString("PleaseEnterThePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the subject.
        /// </summary>
        public static string PleaseEnterTheSubject {
            get {
                return ResourceManager.GetString("PleaseEnterTheSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your message.
        /// </summary>
        public static string PleaseEnterYourMessage {
            get {
                return ResourceManager.GetString("PleaseEnterYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string PleaseEnterYourName {
            get {
                return ResourceManager.GetString("PleaseEnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        public static string PleaseEnteYourEmailAddress {
            get {
                return ResourceManager.GetString("PleaseEnteYourEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Please Select Doctor-.
        /// </summary>
        public static string PleaseSelectDoctor {
            get {
                return ResourceManager.GetString("PleaseSelectDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Please Select Procedure-.
        /// </summary>
        public static string PleaseSelectProcedure {
            get {
                return ResourceManager.GetString("PleaseSelectProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Procedures.
        /// </summary>
        public static string PopularProcedures {
            get {
                return ResourceManager.GetString("PopularProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        public static string Pounds {
            get {
                return ResourceManager.GetString("Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Op Consultation Form.
        /// </summary>
        public static string PreOpConsultationForm {
            get {
                return ResourceManager.GetString("PreOpConsultationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Surgeries?.
        /// </summary>
        public static string PreviousSurgeries {
            get {
                return ResourceManager.GetString("PreviousSurgeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Patient Results.
        /// </summary>
        public static string RealPatientResults {
            get {
                return ResourceManager.GetString("RealPatientResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RealState {
            get {
                return ResourceManager.GetString("RealState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RealStateProfessional {
            get {
                return ResourceManager.GetString("RealStateProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reception.
        /// </summary>
        public static string Reception {
            get {
                return ResourceManager.GetString("Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelatedBlogPosts {
            get {
                return ResourceManager.GetString("RelatedBlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Offers.
        /// </summary>
        public static string RelatedOffers {
            get {
                return ResourceManager.GetString("RelatedOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Services.
        /// </summary>
        public static string RelatedServices {
            get {
                return ResourceManager.GetString("RelatedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RelatedVideos {
            get {
                return ResourceManager.GetString("RelatedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Consultation.
        /// </summary>
        public static string RequestConsultation {
            get {
                return ResourceManager.GetString("RequestConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhinoplasty.
        /// </summary>
        public static string Rhinoplasty {
            get {
                return ResourceManager.GetString("Rhinoplasty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety.
        /// </summary>
        public static string Safety {
            get {
                return ResourceManager.GetString("Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety first.
        /// </summary>
        public static string Safetyfirst {
            get {
                return ResourceManager.GetString("Safetyfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avana Bariatric Surgery meets the highest safety standards. Our experienced team will create a safe and pleasant patient experience for you..
        /// </summary>
        public static string Safetyfirsttext {
            get {
                return ResourceManager.GetString("Safetyfirsttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We continue complying with strict safety standards by conducting regular site visits and customer service satisfaction surveys. Our experienced team will create a safe and pleasant patient experience for you. Dr. Moradian has an operating room team of medical specialists with extensive experience in bariatric surgery. Our staff and medical experts will work closely with you to make sure you enjoy your weight loss journey and establish a long lasting relationship with our practice..
        /// </summary>
        public static string Safetytext {
            get {
                return ResourceManager.GetString("Safetytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SatistiedCustomers {
            get {
                return ResourceManager.GetString("SatistiedCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a consultation.
        /// </summary>
        public static string ScheduleAConsultation {
            get {
                return ResourceManager.GetString("ScheduleAConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule A Free Consultation Today.
        /// </summary>
        public static string ScheduleAFreeConsultationToday {
            get {
                return ResourceManager.GetString("ScheduleAFreeConsultationToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchFAQs {
            get {
                return ResourceManager.GetString("SearchFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Photo Gallery.
        /// </summary>
        public static string SeePhotoGallery {
            get {
                return ResourceManager.GetString("SeePhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Your Language.
        /// </summary>
        public static string SelectYourLanguage {
            get {
                return ResourceManager.GetString("SelectYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services In This Category.
        /// </summary>
        public static string ServicesInThisCategory {
            get {
                return ResourceManager.GetString("ServicesInThisCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we couldn&apos;t find any.
        /// </summary>
        public static string SorryWeCouldntFindAny {
            get {
                return ResourceManager.GetString("SorryWeCouldntFindAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sur.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Details.
        /// </summary>
        public static string SpecialDetails {
            get {
                return ResourceManager.GetString("SpecialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE PATIENT AND ANY OTHER PERSON RESPONSIBLE FOR PAYMENT HAS A RIGHT TO REFUSE TO PAY, CANCEL PAYMENT, OR BE REIMBURSED FOR PAYMENT FOR ANY OTHER SERVICE, EXAMINATION, OR TREATMENT THAT IS PERFORMED AS A RESULT OF AND WITHIN 72 HOURS OF RESPONDING TO THE ADVERTISEMENT FOR THE FREE, DISCOUNTED FEE, OR REDUCED FEE SERVICE, EXAMINATION, OR TREATMENT..
        /// </summary>
        public static string SpecialOfferDisclaimer {
            get {
                return ResourceManager.GetString("SpecialOfferDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials with.
        /// </summary>
        public static string SpecialsWith {
            get {
                return ResourceManager.GetString("SpecialsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        public static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of the art center.
        /// </summary>
        public static string Stateoftheart {
            get {
                return ResourceManager.GetString("Stateoftheart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our spacious and comfortable surgery center combines the latest technology with the most advanced safety features and welcoming aesthetic..
        /// </summary>
        public static string Stateofthearttext {
            get {
                return ResourceManager.GetString("Stateofthearttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StreetAddress {
            get {
                return ResourceManager.GetString("StreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StudentConsent {
            get {
                return ResourceManager.GetString("StudentConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The support you need.
        /// </summary>
        public static string Supportyouneed {
            get {
                return ResourceManager.GetString("Supportyouneed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our dedicated team of caring and experienced specialists will stand by your side to assist you through the whole process from start to finish..
        /// </summary>
        public static string Supportyouneedtext {
            get {
                return ResourceManager.GetString("Supportyouneedtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgeon.
        /// </summary>
        public static string Surgeon {
            get {
                return ResourceManager.GetString("Surgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgeons.
        /// </summary>
        public static string Surgeons {
            get {
                return ResourceManager.GetString("Surgeons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery.
        /// </summary>
        public static string Surgery {
            get {
                return ResourceManager.GetString("Surgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Center.
        /// </summary>
        public static string SurgeryCenter {
            get {
                return ResourceManager.GetString("SurgeryCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Room.
        /// </summary>
        public static string SurgeryRoom {
            get {
                return ResourceManager.GetString("SurgeryRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also known as vertical sleeve gastrectomy and sleeve gastrectomy, gastric sleeve surgery helps limit the amount of food intake by reducing the size of the stomach. This minimally invasive procedure removes a portion of the stomach, leaving a new, smaller banana-shaped stomach. Patients undergoing this procedure feel full after eating much less. Moreover, a gastric sleeve also removes the fragment of the stomach that produces a hormone that makes you feel hungry to encourage loss of appetite and establish he [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Surgerytext {
            get {
                return ResourceManager.GetString("Surgerytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical.
        /// </summary>
        public static string Surgical {
            get {
                return ResourceManager.GetString("Surgical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour of our clinic and its main service rooms.
        /// </summary>
        public static string TakeTour {
            get {
                return ResourceManager.GetString("TakeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Moradian.
        /// </summary>
        public static string TeamDr {
            get {
                return ResourceManager.GetString("TeamDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avana is a top Plastic Surgery Center located in the heart of Miami.  We offer a comprehensive range of services, including cosmetic procedures in high demand, and innovative aesthetic treatments to meet your most challenging cosmetic needs..
        /// </summary>
        public static string teamtext1 {
            get {
                return ResourceManager.GetString("teamtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Avana Plastic Surgery, we sculpt the new you with artistry and skillful hands. Our primary goal is to produce subtle or dramatic results in line with your most cherished aesthetic goals, always keeping in mind your safety and satisfaction..
        /// </summary>
        public static string teamtext2 {
            get {
                return ResourceManager.GetString("teamtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our philosophy of matchless personalized treatment and surgical expertise has attracted many local and out-of-town patients looking to restore their chattered beauty dreams. By taking into consideration each patient&apos;s desires and unique anatomical features, we create “customized” results that last. If you are pondering plastic surgery to help you become your best self, or you are prepared to start your surgical journey, give us a try!.
        /// </summary>
        public static string teamtext3 {
            get {
                return ResourceManager.GetString("teamtext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string TheInPluralAndFemale {
            get {
                return ResourceManager.GetString("TheInPluralAndFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your message.
        /// </summary>
        public static string ThereWasAnErrorSendingYourMessage {
            get {
                return ResourceManager.GetString("ThereWasAnErrorSendingYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeframe.
        /// </summary>
        public static string Timeframe {
            get {
                return ResourceManager.GetString("Timeframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Community During.
        /// </summary>
        public static string ToCommunityDuring {
            get {
                return ResourceManager.GetString("ToCommunityDuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tummy Tuck.
        /// </summary>
        public static string TummyTuck {
            get {
                return ResourceManager.GetString("TummyTuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TypeYourFullName {
            get {
                return ResourceManager.GetString("TypeYourFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UploadYourEssayText {
            get {
                return ResourceManager.GetString("UploadYourEssayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UploadYourTranscriptText {
            get {
                return ResourceManager.GetString("UploadYourTranscriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Us.
        /// </summary>
        public static string Us {
            get {
                return ResourceManager.GetString("Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VideoFAQs {
            get {
                return ResourceManager.GetString("VideoFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ViewAllFemale {
            get {
                return ResourceManager.GetString("ViewAllFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ViewAllVideoFAQs {
            get {
                return ResourceManager.GetString("ViewAllVideoFAQs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW DIRECTIONS.
        /// </summary>
        public static string ViewDirections {
            get {
                return ResourceManager.GetString("ViewDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Gallery.
        /// </summary>
        public static string ViewGallery {
            get {
                return ResourceManager.GetString("ViewGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Instagram.
        /// </summary>
        public static string ViewOnInstagram {
            get {
                return ResourceManager.GetString("ViewOnInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Press Release.
        /// </summary>
        public static string ViewPressRelease {
            get {
                return ResourceManager.GetString("ViewPressRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VisitFaqPageEngagementSentence {
            get {
                return ResourceManager.GetString("VisitFaqPageEngagementSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Us Today.
        /// </summary>
        public static string VisitUsToday {
            get {
                return ResourceManager.GetString("VisitUsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting room.
        /// </summary>
        public static string WaitingRoom {
            get {
                return ResourceManager.GetString("WaitingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking Inside the Center .
        /// </summary>
        public static string WalkInside {
            get {
                return ResourceManager.GetString("WalkInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have come to our site because you are looking for a transformation. It is our goal to empower your life through effective weight loss and boost your health through safe bariatric surgery..
        /// </summary>
        public static string welcometext1 {
            get {
                return ResourceManager.GetString("welcometext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Located in the heart of South Florida, Avana utilizes cutting-edge surgical techniques that yield lasting results for many individuals that find it difficult to lose weight through traditional methods..
        /// </summary>
        public static string welcometext2 {
            get {
                return ResourceManager.GetString("welcometext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We look forward to welcoming you on your first visit..
        /// </summary>
        public static string welcometext3 {
            get {
                return ResourceManager.GetString("welcometext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where Found.
        /// </summary>
        public static string WhereFound {
            get {
                return ResourceManager.GetString("WhereFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to find us?.
        /// </summary>
        public static string WhereToFindUs {
            get {
                return ResourceManager.GetString("WhereToFindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Us.
        /// </summary>
        public static string WhyUS {
            get {
                return ResourceManager.GetString("WhyUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker Compensation.
        /// </summary>
        public static string WorkerCompensation {
            get {
                return ResourceManager.GetString("WorkerCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WorkerCompensationProfessional {
            get {
                return ResourceManager.GetString("WorkerCompensationProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Your Bariatric Surgery Procedure.
        /// </summary>
        public static string YourBariatricSurgery {
            get {
                return ResourceManager.GetString("YourBariatricSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BMI is.
        /// </summary>
        public static string YourBMIis {
            get {
                return ResourceManager.GetString("YourBMIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent to us.
        /// </summary>
        public static string YourMessageHasBeenSentToUs {
            get {
                return ResourceManager.GetString("YourMessageHasBeenSentToUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipCode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
